// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reviq.Infrastructure.Persistence;

#nullable disable

namespace Reviq.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ReviqDbContext))]
    partial class ReviqDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Reviq.Infrastructure.Persistence.Entities.FileReviewRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewResultId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReviewResultId");

                    b.ToTable("FileReviewRecord");
                });

            modelBuilder.Entity("Reviq.Infrastructure.Persistence.Entities.ReviewIssueRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodeAfter")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodeBefore")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FileReviewId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Line")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Suggestion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FileReviewId");

                    b.ToTable("ReviewIssueRecord");
                });

            modelBuilder.Entity("Reviq.Infrastructure.Persistence.Entities.ReviewResultRecord", b =>
                {
                    b.Property<string>("ReviewId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CommitHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Critical")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GeneralFeedback")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Info")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OverallScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RepoPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalIssues")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Warnings")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReviewId");

                    b.HasIndex("CreatedAt");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Reviq.Infrastructure.Persistence.Entities.FileReviewRecord", b =>
                {
                    b.HasOne("Reviq.Infrastructure.Persistence.Entities.ReviewResultRecord", null)
                        .WithMany("Files")
                        .HasForeignKey("ReviewResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Reviq.Infrastructure.Persistence.Entities.ReviewIssueRecord", b =>
                {
                    b.HasOne("Reviq.Infrastructure.Persistence.Entities.FileReviewRecord", null)
                        .WithMany("Issues")
                        .HasForeignKey("FileReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Reviq.Infrastructure.Persistence.Entities.FileReviewRecord", b =>
                {
                    b.Navigation("Issues");
                });

            modelBuilder.Entity("Reviq.Infrastructure.Persistence.Entities.ReviewResultRecord", b =>
                {
                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
